# Compile the pipeline

- name: 'gcr.io/$PROJECT_ID/kfp-cli-vertex'
  id: 'Compile the pipeline'
  args:
  - '-c'
  - |
    dsl-compile-v2 --py pipeline.py --output covertype_kfp_pipeline.json
  env:
  - 'PIPELINE_ROOT=gs://$PROJECT_ID-kfp-artifact-store/pipeline'
  - 'PROJECT_ID=$PROJECT_ID'
  - 'REGION=$_REGION'
  - 'SERVING_CONTAINER_IMAGE_URI=us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.0-20:latest'
  - 'TRAINING_CONTAINER_IMAGE_URI=gcr.io/$PROJECT_ID/trainer_image_covertype_vertex:latest'
  - 'TRAINING_FILE_PATH=gs://$PROJECT_ID-kfp-artifact-store/data/training/dataset.csv'
  - 'VALIDATION_FILE_PATH=gs://$PROJECT_ID-kfp-artifact-store/data/validation/dataset.csv'
  dir: $_PIPELINE_FOLDER/pipeline_vertex

# Run the pipeline
- name: 'gcr.io/$PROJECT_ID/kfp-cli-vertex'
  id: 'Run the pipeline'
  args:
  - '-c'
  - |
    python $_PIPELINE_FOLDER/kfp-cli_vertex/run_pipeline.py --project_id=$PROJECT_ID --template_path=$_PIPELINE_FOLDER/pipeline_vertex/covertype_kfp_pipeline.json --display_name=coverype_kfp_pipeline --region=$_REGION

# Push the images to Container Registry
images: ['gcr.io/$PROJECT_ID/trainer_image_covertype_vertex:latest']

# This is required since the pipeline run overflows the default timeout
timeout: 10800s
